# Generated by Django 5.1.4 on 2024-12-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_person_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_number', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='generation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='person_generation', to='tree.generation'),
            preserve_default=False,
        ),
    ]
