# Generated by Django 5.1.4 on 2024-12-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_alter_person_father_alter_person_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='generation_number',
            field=models.IntegerField(),
        ),
    ]
